services:
  backend:
    image: docker.io/mikkel1510/simple-fortune-cookie-backend:latest
    ports:
      - "9000:9000"

  frontend:
    image: docker.io/mikkel1510/simple-fortune-cookie-frontend:latest
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000
    ports:
      - "8080:8080"
    depends_on:
      - backend
