name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: latest
      - run: |
          echo "$KUBE_CONFIG" | base64 -d > kubeconfig
          kubectl --kubeconfig kubeconfig apply -f manifest.yaml
          kubectl --kubeconfig kubeconfig rollout restart deployment/backend
          kubectl --kubeconfig kubeconfig rollout restart deployment/frontend
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
