name: CD
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: latest
      - run: |
          echo "$KUBE_CONFIG" | base64 -d > kubeconfig
          kubectl --kubeconfig kubeconfig apply \
            -f manifests/production/backend-deployment.yaml \
            -f manifests/production/backend-service.yaml \
            -f manifests/production/frontend-deployment.yaml \
            -f manifests/production/frontend-service.yaml \
            --validate=false
           kubectl --kubeconfig kubeconfig rollout status deploy/backend
           kubectl --kubeconfig kubeconfig rollout status deploy/frontend
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
