name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: latest
      - run: |
          echo "$KUBE_CONFIG" | base64 -d > kubeconfig
          kubectl --kubeconfig kubeconfig apply \
            -f backend-deployment.yaml \
            -f backend-service.yaml \
            -f frontend-deployment.yaml \
            -f frontend-service.yaml \
            --validate=false
           kubectl --kubeconfig kubeconfig rollout status deploy/backend
           kubectl --kubeconfig kubeconfig rollout status deploy/frontend
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
