name: CI
on:
  pull_request:
    branches: ["main"]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.module }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - run: go mod download
      - run: go build ./...

      - name: Run Go unit tests
        run: go test ./... -v

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run integration tests with Docker
        working-directory: .
        run: |
          docker compose -f "docker-compose.yml" up -d
          sleep 10
          bash ./test.sh 
  
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-fortune-cookie-backend:latest
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-fortune-cookie-frontend:latest

